version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
      include: scope
    assignees:
      - "lwjohnst86"

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: build
      include: scope
    assignees:
      - "lwjohnst86"
