project:
  type: seedcase-theme
  render:
    - "docs/*"
    - "index.qmd"

website:
  title: "Seedcase Sprout"
  site-url: "https://sprout.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/seedcase-sprout"
  page-navigation: true
  navbar:
    pinned: true
    title: false
    logo: "_extensions/seedcase-project/seedcase-theme/logos/navbar-logo-seedcase-sprout.svg"
    logo-alt: "Seedcase Sprout logo: Main page"
    left:
      - text: "Guide"
        href: docs/guide/index.qmd
      - text: "Design"
        href: docs/design/index.qmd
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/seedcase-sprout"
        aria-label: "GitHub icon: Source code"
      - icon: house
        href: https://seedcase-project.org
        aria-label: "House icon: Seedcase Project home page"
  sidebar:
    - id: design
      pinned: true
      style: "floating"
      contents:
        - text: "Design"
          href: docs/design/index.qmd
        - section: "Architecture"
          href: docs/design/architecture/index.qmd
          contents:
            - docs/design/architecture/requirements.qmd
            - docs/design/architecture/c4-models.qmd
            - docs/design/architecture/naming.qmd
            - docs/design/architecture/modular-design.qmd
            - docs/design/architecture/user-roles.qmd
        - section: "Implementation"
          href: docs/design/implementation/index.qmd
          contents:
            - docs/design/implementation/outputs.qmd
            - docs/design/implementation/python-functions.qmd
            - docs/design/implementation/app-urls.qmd
    - id: guide
      contents:
        - section: "Guide"
          href: docs/guide/index.qmd
          contents:
            - docs/guide/packages.qmd

# format:
#   seedcase-theme-html:
    # include-before-body:
      # - "includes/site-counter.html"
      # - "includes/contribute.html"

editor:
  markdown:
    wrap: 72
    canonical: true
