services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - persistent_storage:/code/persistent_storage
    environment:
      - DATABASE_URL='postgres://postgres:@postgres:5432/SproutData'
  postgres:
    container_name: postgres
    image: 'postgres'
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - './database.env'
    volumes:
      - pgdata:/var/lib/postgres/data
volumes:
  persistent_storage:
  pgdata:
