services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - persistent_storage:/code/persistent_storage
  database:
    container_name: seedcase_sprout
    image: 'postgres'
    ports:
      - '5432:5432'
    env_file:
      - './database.env'

volumes:
  persistent_storage:
