[tool.poetry]
name = "seedcase-sprout"
version = "0.0.1"
description = "Grow your research data in a structured, modern way that follows best practices."
authors = [
  "Luke W. Johnston <lwjohnst@gmail.com>",
  ""
  ]
readme = "README.md"
homepage = "https://sprout.seedcase-project.org"
repository = "https://github.com/seedcase-project/seedcase-sprout"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/seedcase-project/seedcase-sprout/issues"

[tool.poetry.dependencies]
python = "^3.10"
django = "4.2.8"
ruff = "^0.1.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
