# Generated by Django 4.2.8 on 2024-02-07 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('original_file_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_type', models.CharField(choices=[('INT', 'Whole Number'), ('FLOAT', 'Decimal'), ('TEXT', 'Text'), ('BOOL', 'Yes/No'), ('TIME', 'Time'), ('DATETIME', 'Date+Time')], max_length=10)),
                ('allow_missing_value', models.BooleanField()),
                ('allow_duplicate_value', models.BooleanField()),
                ('table_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablemetadata')),
            ],
        ),
    ]
