---
title: "Command line interface"
---

This document describes the command-line interface (CLI) as a development
reference and to track implementation status.

{{< include /docs/includes/_design-status.qmd >}}

## {{< var done >}} `seedcase-sprout`

`seedcase-sprout` has the following signature:

```bash {filename="Terminal"}
seedcase-sprout <COMMAND> [PARAMETERS]
```

When used on its own, `seedcase-sprout` shows the help message as a shorthand
for `--help`:

```bash {filename="Terminal"}
seedcase-sprout
```

`seedcase-sprout` has several commands: `extract-metadata`, `init-metadata`,
`build-metadata`, and `build-resources`. These commands are described below.

### {{< var done >}} `extract-metadata`

The `extract-metadata` command extracts metadata from a Parquet file and outputs
a Python script with the `ResourceProperties()` dataclass filled in with the
extracted metadata. It is meant to be used with Parquet files in the `staging/`
directory that have the same schema (columns and data types) as the final
resource. It has the signature:

```bash {filename="Terminal"}
seedcase-sprout extract-metadata [PARQUET-PATH] --output/-o [OUTPUT-PATH]
```

```{mermaid}
%%| label: fig-cli-extract-metadata-flow
%%| fig-cap: "The flow of input and output through the CLI `extract-metadata` command."
%%| fig-alt: >-
%%|   Diagram showing the flow of input and output through the CLI
%%|   `extract-metadata` command. The user provides the path to the Parquet file
%%|   and the output file, which are used to generate a Python script with
%%|   extracted metadata.

flowchart LR
    parquet[/"Parquet path<br>[PARQUET-PATH]"/]
    output_opt[/"Output path<br>[--output]"/]
    extract["extract-metadata"]
    output[/"Python script<br>[File]"/]

    parquet --> extract
    output_opt --> extract
    extract --> output
```

### {{< var done >}} `init-metadata`

The `init-metadata` command creates a Python script with metadata fields that
haven't been filled in yet. It creates a Python script with empty
`*Properties()` dataclasses. It has the signature:

```bash {filename="Terminal"}
seedcase-sprout init-metadata [OUTPUT-PATH] --type [TYPE]
```

The `output-path` is the path to the file that will be created (e.g.
`package_properties.py` or `resource1_properties.py`) so that there is full
flexibility and control about where and what name the file will have. The
`--type` determines whether to make a file with metadata for the package overall
(top-level metadata) or for a resource file. The default is the package overall.

Unlike `extract-metadata` when `--type` is `resource`, the output is a Python
script with a `ResourceProperties()` class listing all fields but nothing filled
in yet (all commented out). For resource metadata, the script will have be
manually imported into the package metadata file (since the
`PackageProperties()` contains a field for the `ResourceProperties()`).

```{mermaid}
%%| label: fig-cli-init-metadata-flow
%%| fig-cap: "The flow of input and output through the CLI `init-metadata` command."
%%| fig-alt: >-
%%|   Diagram showing the flow of input and output through the CLI
%%|   `init-metadata` command. The user provides an output path to where the
%%|   file should be created, as well as the type of metadata to create.

flowchart LR
    output_path[/"Path<br>[OUTPUT-PATH]"/]
    type[/"Metadata type<br>[TYPE]"/]
    init["init-metadata"]
    output[/"Python script<br>[File]"/]

    output_path --> init
    type --> init
    init --> output
```

### {{< var wip >}} `build-resources`

The `build-resources` command converts a set of "staging" Parquet files and
converts them into the final resources, along with other additional
functionality (described below). It has the signature:

```bash {filename="Terminal"}
seedcase-sprout build-resources [PROJECT-DIR] --config-file [CONFIG-FILE]
```

The `PROJECT-DIR` defaults to the current working directory. While setting the
`--config-file` is optional, the file itself is required. Because converting
staging Parquet files into the final resources is a bit complex, this file is
used to ensure a reproducible build with clear instructions on what files go
into what resource. If the `--config-file` argument is not set,
`build-resources` and will look in this order for these files:

- `.config/sprout.toml`
- `sprout.toml` or `.sprout.toml`
- `pyproject.toml` (under `[tool.sprout.*]`)

The configurations for the `build-resources` command are under the
`[build-resources]` table. This contains a field and a sub-table:

- `delete-obs-units-file` for a csv file with a list of ["observational
  units"](inputs.qmd) to exclude/delete from the final resources (this is for
  legal and privacy compliance). The filepath is relative to the data package
  root. The file must contain the column name or names that have the IDs for the
  observational unit and the value(s) to exclude. The column(s) should be the
  base unit used across all resources that represents entity of interest. For
  example, the participant ID for the person who has had their data collected
  for the research study. In order for the deletion to work correctly for all
  resources, the given units' columns must also be present in order for the unit
  to be removed.
- `resources` is a list of tables with the resource `name`, the directory where
  the staging Parquet files are kept in `input-dir`, and the final output
  directory where the new, e.g. `<resource-name>.parquet` file will be created
  with `output-dir`. The `name` field is used in place of `<resource-name>`. To
  allow for additional extensions, there is also a (for now) placeholder
  `extras` field.

```toml {.filename="sprout.toml"}
# While top level for Sprout, is also needed for `build-resources`.
metadata-file = ""

[build-resources]
delete-obs-units-file = ""

[[build-resources.resources]]
name = "demographics"
input-dir = "staging/demographics/"
output-dir = "resources/"
# E.g. for making partition or for storing images.
extras = {...}

[[build-resource.resources]]
name = "blood"
input-dir = "staging/blood/"
output-dir = "resources/"
```

For the `units-file`, it should be in a [tidy format](inputs.qmd). It might look
something like:

```text
participant_id,date_id
1,2020-01-01
1,2020-06-01
2,2020-12-31
```

```{mermaid}
%%| label: fig-cli-build-resources-flow
%%| fig-cap: "The flow of input and output through the CLI `build-resources` command."
%%| fig-alt: >-
%%|   Diagram showing the flow of input and output through the CLI
%%|   `build-resources` command. The user optionally provides the path to the
%%|   project directory (that is the data package root) and the path to the
%%|   config file that describes how to build the staging files into resources.

flowchart LR
    config_file[/"Configuration file<br>with build instructions<br>[--config-file]"/]
    project_dir[/"Project directory<br>[PROJECT-DIR]"/]
    build_resources["build-resources"]
    output[/"Resource files<br>[Parquet]"/]

    config_file & project_dir --> build_resources
    build_resources --> output
```

#### Internal flow of functions and objects

```{mermaid}
%%| label: fig-build-resources-internal-flow
%%| fig-cap: >-
%%|   The internal flow of functions and objects in the `build-resources` CLI
%%|   command.
%%| fig-alt: >-
%%|   Diagram of the internal flow of functions and objects in the
%%|   `build-resources` CLI command.

flowchart TD
    %% Inputs, config, metadata
    project_dir:::input --> load_metadata{{"load_metadata()"}} --> metadata[PackageMetadata]
    project_dir --> load_config
    config_file:::input --> load_config{{"load_config()"}} --> Config
    Config --metadata_file--> load_metadata
    metadata --> check_metadata{{"check_metadata()"}} --> metadata_checked[PackageMetadata]

    %% Deleted IDs
    project_dir --> get_deleted_ids{{"get_deleted_ids()"}} --> deleted_ids[pl.DataFrame]
    deleted_ids --> check_deleted_ids{{"check_deleted_ids()"}} --> deleted_ids_checked[pl.DataFrame]
    Config --delete_obs_units_file--> get_deleted_ids
    metadata_checked -- obs_unit_id_cols --> check_deleted_ids

    %% Map over resources
    Config --resources--> resource_configs["list[ResourceConfig]"]
    project_dir --> build_resource
    deleted_ids_checked --> build_resource
    metadata_checked --resources--> build_resource
    resource_configs --map--> build_resource

    subgraph build_resource["build_resource()"]
        direction TB

        get_resource_metadata{{"get_resource_metadata()"}} --> ResourceMetadata
        read_batches{{"read_batches()"}} --> batches["list[Batch(pl.LazyFrame, path, timestamp)]"]
        batches --> check_schema{{"check_schema()"}} --> batches_checked["list[Batch]"]
        ResourceMetadata --> check_schema
        batches_checked --> join_batches{{"join_batches()"}} --> built_data[pl.LazyFrame]
        ResourceMetadata --primary_key--> join_batches
        built_data --> drop_deleted_ids{{"drop_deleted_ids()"}} --> built_data_del[pl.LazyFrame]
        built_data_del --collect--> check_constraints{{"check_constraints()"}} --> built_data_checked[pl.DataFrame]
        ResourceMetadata --> check_constraints
        built_data_checked --> write_data{{"write_data()"}}
    end

    %% Results
    build_resource --> build_results["list[BuildResult(name, path, error)]"]
    build_results --> log_result{{"log_result()"}}

    classDef input fill:#FFF
    style build_resource fill:#FFF, color:#000
```
