---
title: "Python interface"
---

This document describes the design of the Python functions forming the CLI and
the library layer, as well as tracking implementation status.

{{< include /docs/includes/_design-status.qmd >}}

## CLI

### {{< var done >}} `extract_metadata()`

`extract_metadata()` has two arguments: `parquet_path` and `output_path`. The
`parquet_path` argument is the path to a Parquet file in, e.g. the `staging/`
directory, and the `output_path` argument is the path to the Python script that
will have the `ResourceProperties()` dataclass filled in with the extracted
metadata.

```{mermaid}
%%| label: fig-flow-extract-resource-metadata
%%| fig-cap: >-
%%|   Diagram showing the flow of objects and functions to extract a resource's
%%|   metadata from data.
%%| fig-alt: >-
%%|   A flow diagram showing the steps to extract resource metadata from a
%%|   Parquet file.

flowchart
    parquet[/"Parquet data<br>[PARQUET-PATH]"/]
    read_parquet["read_parquet()"]
    output_opt[/"Output path<br>[--output]"/]
    output[/"Python script<br>[File]"/]
    data[("DataFrame<br>(Tidy)")]
    extract_metadata["extract_column_metadata()"]
    metadata[("ResourceProperties<br>(extracted)")]
    init_metadata["init_resource_metadata()"]

    parquet --> read_parquet
    read_parquet --> data
    data --> extract_metadata
    extract_metadata --> metadata -->|render<br>from<br>template| init_metadata
    output_opt --> write["write_file()"]
    init_metadata -->|string| write
    write --> output
```

### {{< var done >}} `init_metadata()`

`init_metadata()` has two arguments: `output_path` and `type`. The `output_path`
argument is the path to where the Python script will be created, which will
contain an empty `PackageProperties()` or `ResourceProperties()` dataclass. The
`type` argument is the type of metadata to create: `package` or `resource`.

```{mermaid}
%%| label: fig-flow-init-metadata
%%| fig-cap: >-
%%|   Diagram showing the flow of objects and functions to compose the metadata
%%|   in a Python script.
%%| fig-alt: >-
%%|   A flow diagram showing the steps to creating the Python file with the
%%|   empty metadata fields.

flowchart
    output_path[/"Output path<br>[output_path]"/]
    type[/"Type of metadata<br>[type]"/]
    template[/"Template<br>[File]"/]
    init_metadata["init_*_metadata()"]
    write_file("write_file()")
    output[/"Python script<br>[File]"/]

    type -->|package<br>or resource| init_metadata
    template --> init_metadata -->|string| write_file
    output_path --> write_file --> output
```

## Library

### {{< var done >}} Metadata classes

These classes contain an explicit, structured set of official metadata defined
for a data package. The main purpose of these classes is to give programmatic
access to the structured metadata. That way the metadata can be generated from
writing Python code that, if it's possible, can processes some input source of
metadata into Sprout's metadata structure. The classes also make it easier to
get an overview or learn about what fields are part of the metadata in Sprout
(e.g. optional vs required fields) and what will be eventually generated into
the final data package. We currently only have metadata classes for the [Data
Package spec](https://datapackage.org).

See the help documentation with `help(SproutProperties())` for more details on
the metadata classes.
