project:
  type: seedcase-theme

website:
  site-url: "https://sprout.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/seedcase-sprout"
  page-footer:
    center:
      - text: "License: CC-BY 4.0"
        href: LICENSE.md
  page-navigation: true
  navbar:
    pinned: true
    logo: "_extensions/seedcase-project/seedcase-theme/logos/navbar-logo-seedcase-sprout.svg"
    logo-alt: Seedcase sprout logo
    left:
      - text: "Design"
        href: design/index.qmd
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/seedcase-sprout"
        aria-label: GitHub
      - icon: house
        href: https://seedcase-project.org
        aria-label: Home page
  sidebar:
    - id: design
      title: "Design"
      pinned: true
      style: "floating"
      align: left
      collapse-level: 1
      contents:
        - auto: design/

# format:
#   seedcase-theme-html:
    # include-before-body:
      # - "includes/site-counter.html"
      # - "includes/contribute.html"

editor:
  markdown:
    wrap: 72
    canonical: true
