@startuml ci-and-cd
skinparam actorStyle awesome
title Continuous Integration and Continuous Delivery


'Continuous Integration -----------------------------------
actor "Software Developer"                  as Developer
(**feature branch**)                        as FeatureBranch
(**main branch**)                           as MainBranch

Developer --> FeatureBranch : Code committed \nto new branch
FeatureBranch --> "Continuous Integration" : "Automatic trigger GitHub actions"
FeatureBranch --> MainBranch : "Feature branch is merged\n into main branch with\na pull request"
MainBranch --> "Continuous Delivery" : "Automatic trigger GitHub actions"

rectangle "Continuous Integration" {
  (Install dependencies)            as dependencies

  (Unit tests)                      as UnitTests
  (Integration tests)               as ItTests
  cloud "Demo environment"          as demo

  dependencies --> UnitTests
  UnitTests --> ItTests
  ItTests --> demo : "If pull request \ndeploy to \ndemo env"
}

rectangle "Continuous Delivery" {
    collections "Run CI\nsteps again"       as all_tests
    artifact "Docker image"                 as docker_image
    database "DockerHub"                    as docker_hub
    cloud "Main demo env"           as main_demo


    all_tests --> docker_image : "Build docker\n image"
    docker_image --> docker_hub : "Push to \nDockerHub"
    docker_hub --> main_demo : "Run image in\ncloud service"
}

@enduml