@startuml package-create-flow
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

skinparam StateFontColor black
skinparam StateFontName Fira Code

state "Input" as input {
' Arguments -----
  path : Path to where packages are stored.
}

state "Output" as output {
  output : The package parent folder is shown as /
  state "packages/<id>/datapackage.json\n/packages/<id>/README.md\n/packages/<id>/resources/" as structure
  structure : The files and folders for a basic data package.
}

state "create_package_structure()" as cps {
  pc : - Required arguments: path



}
' Flow for creating package db 
pfpd --> cdt 
cdt --> cut
cut --> wpd
wpd --> file_sql

' Flow for creating properties
path --> gpd : JSON
gpd --> vpp : JSON
properties --> vpp : JSON: Optionally requires\nuser input\confirmation
pfpp --> wpp : Path object

vpp --> wpp : JSON
wpp --> file_dpj : File
wpp --> file_rm : File

@enduml

