@startuml create-resource-structure
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

skinparam StateFontColor black
skinparam StateFontName Fira Code

state "Input" as input {
  input : - `path_*()` functions assist\n  with giving correct paths
' Arguments -----
  path : - Path to resources\n  folder in a package
}

state "Output" as output {
  output : - The package parent folder is shown as /
  output : - Output: list two paths, the resource path\n  and the resource raw path
  state "/resources/<id>/" as folder_id
  folder_id : Folder with assigned ID (e.g. '1')

  state "/resources/<id>/raw/" as folder_raw
  folder_raw : Raw folder with assigned ID (e.g. '1')
  folder_id --[hidden]> folder_raw
}

state "create_resource_structure()" as crs {
  crs : - Required argument: path

  state arg <<entryPoint>>
  input --> arg

  state "verify_is_directory()" as vid
  vid : - Required arg: path
  vid : - Output: path or Error
  arg --> vid

  state "get_ids()" as gi
  gi : - Required arg: path to resources folder
  gi : - Output: list of existing IDs (or the empty list) 
  vid --> gi

  state "create_next_id()" as cni
  cni : - Required arg: list of existing IDs
  cni : - Output: ID
  gi --> cni

  state "create_resource_path()" as crp
  crp : - Required args:\n    - ID to assign for directory\n    - path to resources folder
  crp : - Output: path to directory for new resource
  cni --> crp

  state "create_dir()" as cd
  cd : - Required arg: path to directory to create
  cd : - Output: path to created directory
  crp --> cd

  state "create_resource_raw_dir()" as crrd
  crrd : - Required arg: path to resource ID
  crrd : - Output: path of created directory
  cd --> crrd

  state join <<join>>
  state return <<exitPoint>>
  crrd --> join
  cd --> join
  join --> return
  return --> output
}

@enduml

