name: Deploy documentation as website

on:
  push:
    branches: 
      - main
    paths:
      - docs/**

jobs:
  build-deploy-docs:
    uses: seedcase-project/.github/.github/workflows/deploy-docs.yml@main
