name: Deploy Demo App

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    uses: seedcase-project/.github/.github/workflows/lint-python.yml@main

  django-test:
    runs-on: ubuntu-latest
    uses: seedcase-project/.github/.github/workflows/test.yml@main
    needs: lint

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: django-test

    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
