name: Deploy Demo App

# Only trigger when pushed/merged to main and after running the tests actions.
on:
  workflow_run:
    workflows: 
      - 'Run tests'
    types: 
      - completed
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    # Only run when test workflow passes.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
