# From: https://github.com/superfly/fly-pr-review-apps
name: Deploy PR Preview App

on:  
  pull_request:  
    types: [opened, reopened, synchronize, closed]  
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - ".github/**"
      - ".vscode/**"
      - "*.md"
      - "*.qmd"
      - ".gitignore"


env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: ams
  FLY_ORG: seedcase-project

jobs:
  lint:
    uses: seedcase-project/.github/.github/workflows/lint-python.yml@main

  django-test:
    uses: seedcase-project/.github/.github/workflows/test.yml@main
    needs: lint

  staging_app:
    runs-on: ubuntu-latest
    needs: django-test

    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy preview of PR
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.0
        with:
          name: ${{ github.event.repository.name }}-pr-${{ github.event.number }}

      # This removes left over items in GitHub from the building and deploying.
      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v3
        if: ${{ github.event.action == 'closed' }}
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.DELETE_ENV_TOKEN }}
          environment: pr-${{ github.event.number }}