name: Deploy Images to Github Container registry

on:
  push:

jobs:
  permissions: write-all
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and publish image'
        run: |
          docker build . --tag ghcr.io/seedcase-project/seedcase-sprout:latest
          docker push ghcr.io/seedcase-project/seedcase-sprout:latest
