name: Deploy to Fly.io

# We want to trigger a deployment in these cases
# - push to main deploys to seedcase-sprout
# - pull requests to main deploys to seedcase-sprout-pr
# - workflow_dispatch allow for manual deployments
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  # sprout is deployed to two different environments based on APP_NAME:
  # - seedcase-sprout on main-branch
  # - seedcase-sprout-pr on pull requests
  APP_NAME: ${{github.ref == 'refs/heads/main' && 'seedcase-sprout' || 'seedcase-sprout-pr'}}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup flyctl tool
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy app to seedcase-sprout or seedcase-sprout-pr
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP: seedcase-sprout-pr
