name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python (with cache for Poetry)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies with Poetry
        run: poetry install --no-interaction --no-root

      - name: Add database migrations to test database
        run: poetry run python manage.py migrate

      - name: Run unit tests
        run: poetry run python manage.py test
